# Generated by Django 6.0.5 on 2026-06-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('hours_played', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_review.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_title', models.TextField()),
                ('review_text', models.TextField()),
                ('recommended', models.BooleanField()),
                ('date_submitted', models.DateTimeField(auto_now=True)),
                ('game_library_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_review.gamelibraryentry')),
            ],
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('developer', models.TextField()),
                ('publisher', models.TextField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('steam_app_id', models.IntegerField(blank=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_review.genre')),
            ],
        ),
        migrations.AddField(
            model_name='gamelibraryentry',
            name='video_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_review.videogame'),
        ),
    ]
