# Generated by Django 6.0.5 on 2026-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='steam_app_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
