# Generated by Django 6.0.5 on 2026-06-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogame',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='videogame',
            name='ai_summary_review_count',
            field=models.IntegerField(default=0),
        ),
    ]
