# Generated by Django 6.0.5 on 2026-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_review', '0002_videogame_ai_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelibraryentry',
            name='status',
            field=models.TextField(choices=[('Want to Play', 'Want to Play'), ('Currently Playing', 'Currently Playing'), ('Played', 'Played')]),
        ),
    ]
